baseURL = "https://tommy-garabedian.netlify.app"
disableLanguages = ["fr"]
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
title = "Red Oak Realty"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 Thomas Garabedian-Cone. All Rights Reserved."
home = ""
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[menu]
footer = []
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[[menu.main]]
URL = "project"
name = "properties"
weight = 2
[[menu.main]]
URL = "service"
name = "Service"
weight = 3
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 4
[[menu.main]]
hasChildren = true
name = "Pages"
weight = 5
[[menu.main]]
URL = "faq"
name = "FAQ"
parent = "Pages"
[[menu.main]]
URL = "pricing"
name = "Pricing"
parent = "Pages"
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 6
[params]
author = "Themefisher"
contact_form_action = "#"
description = "Contact Us"
email = "thomasgarabedian@gmail.com"
google_analitycs_id = ""
location = "1891 Solano Ave, Berkeley, CA 94707"
logo = "images/tommylogo.png"
mobile = "5104991235"
multi_author = false
[params.gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyDXY1EoeE0Ay4b71A1yuJHFTYSdjsSAOkI&callback=initMap"
map_latitude = "37.891771"
map_longitude = "-122.277390"
map_marker = "images/marker.png"
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[params.social]]
icon = "ion-social-instagram-outline"
link = "https://www.instagram.com/tommy_garabedian/"
[[params.social]]
icon = "ion-social-googleplus-outline"
link = "#"
[[params.social]]
icon = "ion-social-linkedin-outline"
link = "#"
[[params.social]]
icon = "ion-social-pinterest-outline"
link = "#"
[[params.social]]
icon = "ion-social-dribbble-outline"
link = "#"
[[params.social]]
icon = "ion-social-twitter-outline"
link = "#"
[[params.social]]
icon = "ion-social-facebook-outline"
link = "#"
